name: Build all wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.68'
        default: 'v0.2.68'
        required: true
        type: string

permissions:
  contents: write

jobs:          
  build_textgen_wheels_windows:
    name: CUDA Wheels Windows
    uses: ./.github/workflows/build-wheels-oobabooga.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-latest'
      exclude: 'avxver:AVX'

  build_wheels_tensorcores_windows:
    name: Tensor Core Windows
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-latest'
      exclude: 'avxver:AVX'


  build_wheels_cpu:
    name: CPU-only Wheels
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-latest'
      exclude: 'avx:AVX'
