name: Build all wheels

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag of llama-cpp-python to build: v0.2.78'
        default: 'v0.2.78'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build_wheels_cpu:
    name: CPU wheels Windows
    uses: ./.github/workflows/build-wheels-cpu.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'
      exclude: 'avx:AVX'
      
  build_wheels_cuda:
    name: CUDA wheels Windows
    uses: ./.github/workflows/build-wheels-cuda.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'
      exclude: 'avxver:AVX'

  build_wheels_tensorcores:
    name: TensorCores wheels Windows
    uses: ./.github/workflows/build-wheels-tensorcores.yml
    with:
      version: ${{ inputs.version }}
      config: 'os:windows-2019'
      exclude: 'avxver:AVX'
